version: '3'
services:
  haproxy:
    image: eeacms/haproxy
    depends_on:
    - apinodejs
    ports:
    - "3001:3001"
    - "1936:1936"
    environment:
      BACKENDS: "apinodejs"
      DNS_ENABLED: "true"
      LOG_LEVEL: "info"
  apinodejs:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: apinodejs
    ports:
      - "3000:3001"
    expose: 
      - "3000"
    deploy:
      mode: replicated
      replicas: 5
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure